version: '3'
services:
  orderdishes:
    image: moderras/orderdishes:latest
    env_file: .env
    ports:
      - 65323:80
    volumes:
      - /tmp/orderdishes:/tmp
      - ./db:/data/
    depends_on:
      - redis
    restart: always
  redis:
    image: bitnami/redis:latest
    restart: always
    env_file: .env
    volumes:
      - ./redis:/bitnami/redis/data