version: '3'
services:
  orderdishes:
    image: moderras/orderdishes:latest
    env_file: .env
    ports:
      - 80:80
    volumes:
      - /tmp/orderdishes:/tmp
      - ./db:/data/
    depends_on:
      - redis
    restart: always
  redis:
    image: redis
    restart: always